## Default-Target
all: tollesProgramm

## Baue "TollesProgramm"
tollesProgramm: HelloWorld.c
	gcc -o tollesProgramm HelloWorld.c

## Lasse Programm laufen
run: tollesProgramm
	./tollesProgramm

## Aufraeumen 
clean:
	rm -rf tollesProgramm
